version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_containers
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build: ./api
    container_name: api_containers
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - MONGODB_URL=mongodb://mongo:27017/yourdb  # Change this line

  client:
    build: ./client
    container_name: client_containers
    ports:
      - "3003:3003"
    depends_on:
      - api
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /client/node_modules

volumes:
  mongo_data: